### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by demobox**
Minor text tweaks and some additional links.

### CODE REVIEW

**Comment by xlcommunity** [comment]
> Failed — The Travis CI build failed 

@berniedurfee-ge: I **hope** this isn't related to a README change! ;-)

**Comment by demobox** [comment]
> Failed — The Travis CI build failed

@berniedurfee-ge: I hope this isn't related to a README change! ;-)

**Comment by berniedurfee-ge** [comment]
Master branch isn't up-to-date with the Rakefile, so Travis is failing. I'm using gitflow, so changes should go to the develop branch, but no big deal. I'll merge and cut a new release, that should fix Travis.

**Comment by xlcommunity** [comment]
> berniedurfee-ge merged commit

Thanks, @berniedurfee-ge!

**Pull request merged**
